import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F1F8F4" },
  header: { paddingHorizontal: 20, paddingTop: 12, paddingBottom: 8 },
  title: { fontSize: 24, fontWeight: "700", color: "#173B35" },
  subtitleRow: { flexDirection: "row", alignItems: "center", marginTop: 4, gap: 8 },
  subtitle: { fontSize: 13, color: "#628078", marginTop: 4 },
  spinner: { color: "#16856A" },
  grid: {
    flex: 1,
    flexDirection: "row",
    flexWrap: "wrap",
    alignContent: "center",
    justifyContent: "center",
    paddingHorizontal: "3%",
    paddingVertical: 12,
  },
  logPanel: {
    marginTop: "auto",
    paddingHorizontal: 20,
    paddingVertical: 16,
    borderTopWidth: 1,
    borderTopColor: "#CFE3D9",
  },
  logTitle: { fontSize: 11, letterSpacing: 1, color: "#52756D", marginBottom: 8 },
  logEmpty: { fontSize: 13, color: "#52756D" },
  logRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 6,
    borderBottomWidth: 1,
    borderBottomColor: "#DCEBE3",
  },
  logValue: {
    width: 28,
    height: 28,
    borderRadius: 6,
    backgroundColor: "#D7F0E5",
    color: "#13765F",
    textAlign: "center",
    textAlignVertical: "center",
    fontWeight: "700",
    marginRight: 12,
    overflow: "hidden",
  },
  logTime: { flex: 1, color: "#628078", fontSize: 12 },
  logStatus: { fontSize: 12, color: "#628078", textTransform: "uppercase" },
  statusSent: { color: "#16805C" },
  statusFailed: { color: "#C84B4B" },
});
